config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "books#index"

  # construcción del path para acceder al controlador#metodo
  patch "/books/:id/reserve", to: "books#reserve", as: "reserve"
  patch "/books/:id/not_reserve", to: "books#not_reserve", as: "not_reserve"
  patch "/books/:id/buy", to: "books#buy", as: "buy"
  patch "/books/:id/not_buy", to: "books#not_buy", as: "not_buy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional: true
  enum status: [:available, :reserved, :purchased, :deleted]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy reserve not_reserve buy not_buy]
  before_action :authenticate_user!, only: [ :reserve, :destroy, , :buy, :show, :edit]

  # GET /books or /books.json
  def index
    @books_available = Book.where(status: :available)
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    self.select_status
  end

  # GET /books/1/edit
  def edit
    self.select_status
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def reserve
    respond_to do |format|
      if @book.update!(status: 1, user: current_user)
        sleep 1.seconds
        format.js { render nothing: true, notice: 'El libro fue reservado.' }
      end
    end
  end

  def not_reserve
    respond_to do |format|
      if @book.update!(status: 0, user: nil)
        format.js { render nothing: true, notice: 'El libro ya no está reservado.' }
      end
    end
  end

  def buy
    respond_to do |format|
      if @book.update!(status: 2, user: current_user)
        format.js { render nothing: true, notice: 'El libro fue comprado.' }
      end
    end
  end

  def not_buy
    respond_to do |format|
      if @book.update!(status: 3, user: current_user)
        format.js { render nothing: true }
      end
    end
  end

  def select_status
    @statuses = Book.statuses.keys.to_a
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :status, :code)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user = current_user
    @books = @user.books.reserved
    @purchased = @user.books.purchased
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<tr id="book-<%=book.id%>">
  <td><%= book.title %></td>
  <td><%= book.author %></td>
  <td><%= book.status %></td>
  <td><%= book.code %></td>
  <td><%= link_to 'Borrar', not_buy_path(book.id), method: :patch, remote: true, data: { confirm: "¿Está seguro?\n\nNo le reembolsaremos su dinero" } %></td>
</tr>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, @statuses, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/buy.js.erb
$('#book-<%=@book.id%>').remove();
$('#purchased').append('<%= escape_javascript(render(:partial => "books/book", :locals => {:book => @book})) %>');

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Status</th>
      <th>Code</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @books_available.each do |book| %>
      <tr id="book-<%= book.id %>">
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.status %></td>
        <td><%= book.code %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Reserve', reserve_path(book.id), method: :patch, remote: true, data: { disable_with: 'Generando reserva...' } %></td>
          <% else %>
          <td><%= link_to 'Reserve', user_session_path %></td>
        <% end %>
        <% if user_signed_in? %>
          <td><%= link_to 'Show', book %></td>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/not_buy.js.erb
$('#book-<%=@book.id%>').remove();

app/views/books/not_reserve.js.erb
$('#book-<%=@book.id%>').remove();

app/views/books/reserve.js.erb
$('#book-<%=@book.id%>').remove();

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Status:</strong>
  <%= @book.status %>
</p>

<p>
  <strong>Code:</strong>
  <%= @book.code %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortalLibros</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <span>
      <% if user_signed_in? %>
        <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %> |
        <%= link_to 'Mis reservas', current_user %>
        <% else %>
        <%= link_to 'Iniciar Sesión', user_session_path %> |
        <%= link_to 'Home', root_path %>
      <% end %>
    </span>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservados</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Status</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr id="book-<%=book.id%>">
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.status %></td>
        <td><%= book.code %></td>
        <td><%= link_to 'Quitar de la reserva', not_reserve_path(book.id), method: :patch, remote: true %></td>
        <td><%= link_to 'Comprar', buy_path(book.id), method: :patch, remote: true %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Comprados</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Status</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="purchased">
    <% @purchased.each do |book| %>
      <tr id="book-<%=book.id%>">
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.status %></td>
        <td><%= book.code %></td>
        <td><%= link_to 'Borrar', not_buy_path(book.id), method: :patch, remote: true, data: { confirm: "¿Está seguro?\n\nNo le reembolsaremos su dinero" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>